title: ANZ Institutional Digital Developer Portal
author: Australia and New Zealand Banking Group Limited (ANZ) 2022 ABN 11 005 357 522.
email: fileactivesupport@anz.com
description: >-
  Utilising ANZ's suite of API's, ANZ Wholesale Digital  API will enable your organisation to complete near real-time banking with our Institutional Bank services. 
baseurl: "/"
url: ""

repo: "https://github.com/anz-insto"
github_repo: "docs"
github_branch: "master"

# Build settings
theme: minima
markdown: kramdown
highlighter: rouge
input: GFM

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      title: ANZ Institutional Digital Developer Portal

# Collections
collections:
  fileactive:
    output: true
    permalink: /:collection/:path
